
# We recover the image that we want to deploy in the environment 
image:
  repository: antonkad/wobucket
  tag: 1.0.0-rc.1

# Here we retrieve secrets from the vault dedicated to the environment
#
# ...


ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  #  - host: wobucket-prod.local
  #    paths:
  #      - path: /
  #        pathType: ImplementationSpecific
  ## @param ingress.tls ToDo
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
